name: Question
description: Ask a question about using Gohan
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Gohan? We're here to help! Please check the documentation first, and then provide details about your question.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've done the following before asking your question
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
        - label: This is not a bug report or feature request

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about Gohan?
      placeholder: I'm trying to understand how to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish? Provide some background about your use case.
      placeholder: I'm building a blog that needs to...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What approaches have you already attempted?
      placeholder: I tried...

  - type: textarea
    id: config
    attributes:
      label: Current Configuration
      description: If relevant, please share your current configuration
      render: yaml
      placeholder: |
        site:
          title: "My Blog"
        build:
          content_dir: "content"

  - type: input
    id: version
    attributes:
      label: Gohan Version
      description: What version of Gohan are you using?
      placeholder: v1.0.0

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: Which area is your question about?
      options:
        - Getting started
        - Configuration
        - Content creation
        - Templates
        - CLI usage
        - Build process
        - Deployment
        - Troubleshooting
        - Best practices
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question?
      placeholder: Additional context...
