package model

import (
	"html/template"
	"time"
)

// Article is the raw data parsed from a Markdown file.
type Article struct {
	FrontMatter  FrontMatter
	RawContent   string
	FilePath     string
	LastModified time.Time
}

// ProcessedArticle holds derived data generated by the renderer.
type ProcessedArticle struct {
	Article
	HTMLContent template.HTML
	Summary     string
	OutputPath  string
	// ContentPath is the content-dir-relative path to the source Markdown file
	// (e.g. "posts/hello-world.md"). Used to generate GitHub edit/view links.
	ContentPath string
	// Locale is the locale code detected from the content path (e.g. "en", "ja").
	// Empty when i18n is not configured.
	Locale string
	// URL is the canonical URL path for this article (e.g. "/posts/hello/" or
	// "/ja/posts/hello/"). Empty when i18n is not configured.
	URL string
	// Translations lists translated variants of this article, keyed by locale.
	// Populated by BuildTranslationMap after article processing.
	Translations []LocaleRef
	// PluginData holds per-article data injected by enabled plugins.
	// Access in templates: {{index .PluginData "amazon_books"}}
	PluginData map[string]interface{}
	// WordCount is the number of words in the article body. For CJK content
	// each character is counted as one word.
	WordCount int
	// ReadingTime is the estimated reading time in minutes, with a minimum of 1.
	ReadingTime int
	// TOC is the hierarchical table of contents extracted from the article's
	// Markdown headings. Empty when the article has no headings.
	TOC []TOCEntry
}

// TOCEntry represents a single Markdown heading in the table of contents.
// Entries are nested via Children to reflect heading levels.
type TOCEntry struct {
	// Level is the Markdown heading level (1-6).
	Level int
	// ID is the auto-generated heading anchor (matches the rendered HTML id attribute).
	ID string
	// Text is the heading's plain-text content.
	Text string
	// Children holds nested headings (one level deeper) that appear under this entry.
	Children []TOCEntry
}

// LocaleRef holds a locale code and the canonical URL for a translated variant
// of an article. Used to generate language-switcher links in templates.
type LocaleRef struct {
	Locale string
	URL    string
}

// FrontMatter holds the YAML metadata from the top of a Markdown file.
type FrontMatter struct {
	Title       string    `yaml:"title"`
	Date        time.Time `yaml:"date"`
	LastMod     time.Time `yaml:"lastmod"`
	Draft       bool      `yaml:"draft"`
	Tags        []string  `yaml:"tags"`
	Categories  []string  `yaml:"categories"`
	Description string    `yaml:"description"`
	Author      string    `yaml:"author"`
	Slug        string    `yaml:"slug"`
	Template    string    `yaml:"template"`
	// TranslationKey links this article to its translations in other locales.
	// Articles sharing the same key are treated as translations of each other,
	// enabling language-switcher links via ProcessedArticle.Translations.
	TranslationKey string `yaml:"translation_key"`
	// ListingSlugs declares an ordered list of article slugs for curated
	// listing pages.  When non-empty the generator resolves these slugs and
	// exposes them via Site.ListingArticles for template rendering.
	ListingSlugs []string `yaml:"listing_slugs"`
	// Extra captures any front-matter keys not listed above.
	// Plugins read their configuration from this field.
	Extra map[string]interface{} `yaml:",inline"`
}
