// Package model defines all shared data types used across gohan packages.
package model

import (
	"html/template"
	"time"
)

// Article is the raw data parsed from a Markdown file.
type Article struct {
	FrontMatter  FrontMatter
	RawContent   string
	FilePath     string
	LastModified time.Time
}

// ProcessedArticle holds derived data generated by the renderer.
type ProcessedArticle struct {
	Article
	HTMLContent template.HTML
	Summary     string
	OutputPath  string
}

// FrontMatter holds the YAML metadata from the top of a Markdown file.
type FrontMatter struct {
	Title       string    `yaml:"title"`
	Date        time.Time `yaml:"date"`
	Draft       bool      `yaml:"draft"`
	Tags        []string  `yaml:"tags"`
	Categories  []string  `yaml:"categories"`
	Description string    `yaml:"description"`
	Author      string    `yaml:"author"`
	Slug        string    `yaml:"slug"`
	Template    string    `yaml:"template"`
}

// Config is the top-level structure of config.yaml.
type Config struct {
	Site    SiteConfig             `yaml:"site"`
	Build   BuildConfig            `yaml:"build"`
	Theme   ThemeConfig            `yaml:"theme"`
	Plugins map[string]interface{} `yaml:"plugins"`
}

// SiteConfig holds site-wide metadata.
type SiteConfig struct {
	Title       string `yaml:"title"`
	Description string `yaml:"description"`
	BaseURL     string `yaml:"base_url"`
	Language    string `yaml:"language"`
}

// BuildConfig holds build-time directory and parallelism settings.
type BuildConfig struct {
	ContentDir   string   `yaml:"content_dir"`
	OutputDir    string   `yaml:"output_dir"`
	AssetsDir    string   `yaml:"assets_dir"`
	ExcludeFiles []string `yaml:"exclude_files"`
	Parallelism  int      `yaml:"parallelism"`
}

// ThemeConfig holds theme name, directory, and custom parameters.
type ThemeConfig struct {
	Name   string            `yaml:"name"`
	Dir    string            `yaml:"dir"`
	Params map[string]string `yaml:"params"`
}

// Taxonomy represents a single tag or category entry.
type Taxonomy struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

// TaxonomyRegistry holds the master lists loaded from taxonomy YAML files.
type TaxonomyRegistry struct {
	Tags       []Taxonomy `yaml:"tags"`
	Categories []Taxonomy `yaml:"categories"`
}

// BuildManifest is the build history persisted to .gohan/cache/manifest.json.
type BuildManifest struct {
	Version      string              `json:"version"`
	BuildTime    time.Time           `json:"build_time"`
	LastCommit   string              `json:"last_commit"`
	FileHashes   map[string]string   `json:"file_hashes"`
	Dependencies map[string][]string `json:"dependencies"`
	OutputFiles  []OutputFile        `json:"output_files"`
}

// OutputFile records metadata for a single generated file.
type OutputFile struct {
	Path         string    `json:"path"`
	Hash         string    `json:"hash"`
	Size         int64     `json:"size"`
	LastModified time.Time `json:"last_modified"`
	ContentType  string    `json:"content_type"`
}

// NodeType classifies a node in the dependency graph.
type NodeType int

const (
	NodeTypeArticle NodeType = iota
	NodeTypeTag
	NodeTypeCategory
	NodeTypeArchive
	NodeTypePage
)

// Node is a vertex in the dependency graph.
type Node struct {
	Path         string
	Type         NodeType
	Dependencies []string
	Dependents   []string
	LastModified time.Time
}

// DependencyGraph is a directed graph of content dependencies.
type DependencyGraph struct {
	Nodes map[string]*Node
	Edges map[string][]string
}

// ChangeSet holds the result of diff detection between two builds.
type ChangeSet struct {
	ModifiedFiles []string
	AddedFiles    []string
	DeletedFiles  []string
}

// Site holds the full rendering context passed to templates.
type Site struct {
	Config     Config
	Articles   []*ProcessedArticle
	Tags       []Taxonomy
	Categories []Taxonomy
}

// FileWatcher is the interface for watching file system changes.
type FileWatcher interface {
	Add(path string) error
	Events() <-chan string
	Close() error
}

// DevServer is the local HTTP development server configuration.
type DevServer struct {
	Host    string
	Port    int
	OutDir  string
	Watcher FileWatcher
}
