// Package model defines all shared data types used across gohan packages.
package model

import (
"html/template"
"time"
)

// Article is the raw data parsed from a Markdown file.
type Article struct {
FrontMatter  FrontMatter
RawContent   string
FilePath     string
LastModified time.Time
}

// ProcessedArticle holds derived data generated by the renderer.
type ProcessedArticle struct {
Article
HTMLContent template.HTML
Summary     string
OutputPath  string
}

// FrontMatter holds the YAML metadata from the top of a Markdown file.
type FrontMatter struct {
Title       string
Date        time.Time
Draft       bool
Tags        []string
Categories  []string
Description string
Author      string
Slug        string
Template    string
}

// Config is the top-level structure of config.yaml.
type Config struct {
Site    SiteConfig
Build   BuildConfig
Theme   ThemeConfig
Plugins map[string]interface{}
}

// SiteConfig holds site-wide metadata.
type SiteConfig struct {
Title       string
Description string
BaseURL     string
Language    string
}

// BuildConfig holds build-time directory and parallelism settings.
type BuildConfig struct {
ContentDir   string
OutputDir    string
AssetsDir    string
ExcludeFiles []string
Parallelism  int
}

// ThemeConfig holds theme name, directory, and custom parameters.
type ThemeConfig struct {
Name   string
Dir    string
Params map[string]string
}

// Taxonomy represents a single tag or category entry.
type Taxonomy struct {
Name        string
Description string
}

// TaxonomyRegistry holds the master lists loaded from taxonomy YAML files.
type TaxonomyRegistry struct {
Tags       []Taxonomy
Categories []Taxonomy
}

// BuildManifest is the build history persisted to .gohan/cache/manifest.json.
type BuildManifest struct {
Version      string
BuildTime    time.Time
LastCommit   string
FileHashes   map[string]string
Dependencies map[string][]string
OutputFiles  []OutputFile
}

// OutputFile records metadata for a single generated file.
type OutputFile struct {
Path         string
Hash         string
Size         int64
LastModified time.Time
ContentType  string
}

// NodeType classifies a node in the dependency graph.
type NodeType int

const (
NodeTypeArticle  NodeType = iota
NodeTypeTag
NodeTypeCategory
NodeTypeArchive
NodeTypePage
)

// Node is a vertex in the dependency graph.
type Node struct {
Path         string
Type         NodeType
Dependencies []string
Dependents   []string
LastModified time.Time
}

// DependencyGraph is a directed graph of content dependencies.
type DependencyGraph struct {
Nodes map[string]*Node
Edges map[string][]string
}

// ChangeSet holds the result of diff detection between two builds.
type ChangeSet struct {
ModifiedFiles []string
AddedFiles    []string
DeletedFiles  []string
}

// Site holds the full rendering context passed to templates.
type Site struct {
Config     Config
Articles   []*ProcessedArticle
Tags       []Taxonomy
Categories []Taxonomy
}

// FileWatcher is the interface for watching file system changes.
type FileWatcher interface {
Add(path string) error
Events() <-chan string
Close() error
}

// DevServer is the local HTTP development server configuration.
type DevServer struct {
Host    string
Port    int
OutDir  string
Watcher FileWatcher
}
